### ISSUE TITLE
GenericParam panicked

### ISSUE THREAD

**Issue by q6r** [kurotych/sipcore#32]
https://github.com/kurotych/sipcore/blob/e018d3424ef1e43490b308bf04d34e266e40f687/crates/sipmsg/src/headers/generic_params.rs#L38

in some possible invalid input this causes panic

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error(SipParseError { code: 1, message: Some("take_until_nonescaped_quote error!") })'
```

better propagate like the rest of code in `GenericParam`

**Comment by kurotych** [comment]
Hello @q6r , Thank you for contribution. Fix was merged to master and included to 0.2.2 version.
